# Generated by Django 2.2.14 on 2021-01-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Назва')),
                ('article_text', models.TextField(verbose_name='Текст статті')),
                ('keywords', models.CharField(default='keywords', max_length=120, verbose_name='Ключові слова')),
                ('imagin1', models.ImageField(upload_to='articles/', verbose_name='Картинка 1')),
                ('imagin2', models.ImageField(blank=True, upload_to='articles/', verbose_name='Картинка 2')),
                ('imagin3', models.ImageField(blank=True, upload_to='articles/', verbose_name='Картинка 3')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Дата публікації')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Редаговано')),
                ('link1', models.URLField(blank=True, verbose_name='Кнопка 1')),
                ('link1_name', models.TextField(blank=True, verbose_name='Назва кнопки 1')),
                ('link2', models.URLField(blank=True, verbose_name='Кнопка 2')),
                ('link2_name', models.TextField(blank=True, verbose_name='Назва кнопки 2')),
                ('link3', models.URLField(blank=True, verbose_name='Кнопка 3')),
                ('link3_name', models.TextField(blank=True, verbose_name='Назва кнопки 3')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-id', '-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('author', models.CharField(max_length=50, verbose_name='Імя коментатора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст коментаря')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': 'Коментарій',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
