# Generated by Django 2.2.14 on 2021-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації'),
        ),
    ]
