# Generated by Django 2.2.16 on 2021-06-05 16:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210113_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='imagin2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='imagin3',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='imagin1',
            field=models.ImageField(upload_to='articles/', verbose_name='Картинка превю'),
        ),
    ]
