# Generated by Django 2.2.14 on 2021-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='author',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_text',
        ),
        migrations.AddField(
            model_name='team',
            name='capitan',
            field=models.CharField(default='', max_length=50, verbose_name='Капітан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='contact_capitan',
            field=models.CharField(default='', max_length=200, verbose_name='Звязок з капітаном'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_dop',
            field=models.TextField(default='', verbose_name='Запасні гравці'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_osn',
            field=models.TextField(default='', verbose_name='Члени команди і їх посилання на Steam , університет/факультет/група'),
            preserve_default=False,
        ),
    ]
