# Generated by Django 2.2.14 on 2021-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210113_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='', max_length=100, verbose_name='Назва команди'),
            preserve_default=False,
        ),
    ]
