# Generated by Django 2.2.14 on 2021-01-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_team_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-id', '-post_date'], 'verbose_name': 'Турнір', 'verbose_name_plural': 'Турніри'},
        ),
    ]
