# Generated by Django 2.2.14 on 2021-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20210113_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_dop',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_osn',
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_1',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_2',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_3',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_4',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_5',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fuck_6',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_1',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_2',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_3',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_4',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_5',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='group_6',
            field=models.TextField(default='', verbose_name='Група'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_1',
            field=models.TextField(default='', verbose_name='ПІ командира (1-го учасника)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_2',
            field=models.TextField(default='', verbose_name='ПІ 2-го учасника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_3',
            field=models.TextField(default='', verbose_name='ПІ 3-го учасника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_4',
            field=models.TextField(default='', verbose_name='ПІ 4-го учасника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_5',
            field=models.TextField(default='', verbose_name='ПІ 5-го учасника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_6',
            field=models.TextField(default='', verbose_name='ПІ запасного учасника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_1',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_2',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_3',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_4',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_5',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_6',
            field=models.TextField(default='', verbose_name='Лінк на Steam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_1',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_2',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_3',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_4',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_5',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_6',
            field=models.TextField(default='', verbose_name='Університет'),
            preserve_default=False,
        ),
    ]
