# Generated by Django 2.2.14 on 2021-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20210113_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fuck_7',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AddField(
            model_name='team',
            name='group_7',
            field=models.TextField(blank=True, verbose_name='Група'),
        ),
        migrations.AddField(
            model_name='team',
            name='player_name_7',
            field=models.TextField(blank=True, verbose_name='ПІ запасного учасника 2'),
        ),
        migrations.AddField(
            model_name='team',
            name='steam_link_7',
            field=models.TextField(blank=True, verbose_name='Лінк на Steam'),
        ),
        migrations.AddField(
            model_name='team',
            name='vuz_7',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_dop',
            field=models.IntegerField(default=2, verbose_name='Кількість запасних учасників (0-2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_osn',
            field=models.IntegerField(default=5, verbose_name='Кількість учасників (2-5)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='fuck_3',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fuck_4',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fuck_5',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fuck_6',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group_3',
            field=models.TextField(blank=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group_4',
            field=models.TextField(blank=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group_5',
            field=models.TextField(blank=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group_6',
            field=models.TextField(blank=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_name_3',
            field=models.TextField(blank=True, verbose_name='ПІ 3-го учасника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_name_4',
            field=models.TextField(blank=True, verbose_name='ПІ 4-го учасника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_name_5',
            field=models.TextField(blank=True, verbose_name='ПІ 5-го учасника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_name_6',
            field=models.TextField(blank=True, verbose_name='ПІ запасного учасника 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='steam_link_3',
            field=models.TextField(blank=True, verbose_name='Лінк на Steam'),
        ),
        migrations.AlterField(
            model_name='team',
            name='steam_link_4',
            field=models.TextField(blank=True, verbose_name='Лінк на Steam'),
        ),
        migrations.AlterField(
            model_name='team',
            name='steam_link_5',
            field=models.TextField(blank=True, verbose_name='Лінк на Steam'),
        ),
        migrations.AlterField(
            model_name='team',
            name='steam_link_6',
            field=models.TextField(blank=True, verbose_name='Лінк на Steam'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vuz_3',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vuz_4',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vuz_5',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vuz_6',
            field=models.TextField(blank=True, verbose_name='Університет'),
        ),
    ]
