# Generated by Django 2.2.14 on 2021-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20210114_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rate_1',
            field=models.TextField(default='', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='rate_2',
            field=models.TextField(default='', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='rate_3',
            field=models.TextField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='team',
            name='rate_4',
            field=models.TextField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='team',
            name='rate_5',
            field=models.TextField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='team',
            name='rate_6',
            field=models.TextField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='team',
            name='rate_7',
            field=models.TextField(blank=True, verbose_name='Рейтинг'),
        ),
    ]
