# Generated by Django 2.2.14 on 2021-01-20 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20210115_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='deadline_reg',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час закінчення реєстрації'),
            preserve_default=False,
        ),
    ]
