# Generated by Django 2.2.16 on 2021-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20210527_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact_capitan',
            field=models.TextField(max_length=200, verbose_name='Звязок з капітаном'),
        ),
    ]
