# Generated by Django 2.2.16 on 2021-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20210528_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команди'},
        ),
        migrations.AlterField(
            model_name='team',
            name='capitan',
            field=models.TextField(verbose_name='Капітан'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_capitan',
            field=models.TextField(max_length=200, verbose_name='Зв`язок з капітаном'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dop_team_list',
            field=models.TextField(verbose_name='Запасні учасники'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_list',
            field=models.TextField(verbose_name='Основні учасники'),
        ),
    ]
