# Generated by Django 2.2.14 on 2021-01-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Про сайт',
                'verbose_name_plural': 'Про сайт',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Downl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файли',
            },
        ),
        migrations.CreateModel(
            name='Imagin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagin_url', models.URLField(verbose_name='адреса картинки')),
                ('title', models.TextField(verbose_name='Назва')),
                ('texte', models.TextField(verbose_name='Текст')),
                ('bath_title', models.TextField(verbose_name='Текст кнопки')),
                ('batn_url', models.URLField(verbose_name='Адреса для кнопки')),
            ],
            options={
                'verbose_name': 'Картинка на прокрутці',
                'verbose_name_plural': 'Картинки на прокруці',
            },
        ),
        migrations.CreateModel(
            name='Topx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': 'Стаття на головній',
                'verbose_name_plural': 'Статті на головній',
            },
        ),
    ]
