# Generated by Django 2.2.16 on 2021-05-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(verbose_name='ПІ командира (1-го учасника)')),
                ('steam_link', models.TextField(verbose_name='лінк на steam')),
                ('vuz', models.TextField(verbose_name='університет')),
                ('fuck', models.TextField(verbose_name='університет')),
                ('group', models.TextField(verbose_name='група')),
                ('rate', models.TextField(verbose_name='рейтинг')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
