# Generated by Django 2.2.16 on 2021-05-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
