# Generated by Django 2.2.16 on 2021-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210605_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topx',
            name='top_article',
            field=models.IntegerField(verbose_name='ID статті'),
        ),
    ]
