# Generated by Django 2.2.16 on 2021-06-11 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210611_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abou',
            name='about_text',
            field=ckeditor.fields.RichTextField(verbose_name='Про сайт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_text',
            field=ckeditor.fields.RichTextField(verbose_name='Контакти'),
        ),
    ]
